base_url = "https://deal.digital"
title = "deal.digital"
description = "Wesley Deal's Personal Site"
default_language = "en"
build_search_index = true

author = "Wesley Deal"

generate_feeds = true

taxonomies = [
	{name = "author", feed = false},
	{name = "tags", feed = true, render = false},
]

[extra]
stylesheet = "style"
breadcrumbs = false
