# On every push this script is executed
name: Build and deploy GH Pages (zola)

on:
  push:
    branches:
     - master

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build and deploy site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
      - name: Render Resume PDF
        uses: markwilson/html2pdf@v1.0
        with:
          htmlPath: 'static/resume/index.html'
          pdfName: 'static/resume'
      - name: Build
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_FLAGS: --output-dir out
          OUT_DIR: out
